const hyyzvoices = {
	...{//骊歌
		'hyyz_xt_jingyuan': '久疏战阵了……',
		'hyyzshenjun1': '兵戈，无情！',
		'hyyzshenjun2': '雷霆，在此！',
		'hyyzzhankan1': '该出奇兵了。',
		'hyyzzhankan2': '惶惶威灵，遵吾敕命，斩无赦！',
		'hyyzshence1': '临军对阵，持重待机便可。',
		'hyyzshence2': '急如律令。',
		'hyyzshence3': '随我冲阵！',
		'hyyzshence4': '时不我待！',

		'hyyz_xt_qingque': '不想……回去工作……',
		'hyyzlaoyue1': '算了也白算，等等牌就来。',
		'hyyzlaoyue2': '战局如牌局，见机就行事。',
		'hyyzlaoyue3': '牌势无定势，越急越没事。',
		'hyyzlaoyue4': '手握顺风局，闷声发大财。',
		'hyyzlaoyue5': '撞上逆风局，少输就是赢。',
		'hyyzlaoyue6': '不慌。',
		'hyyzlaoyue7': '有了！',
		'hyyzlaoyue8': '来吧！',
		'hyyzlaoyue9': '豁哟！',
		'hyyzlaoyue10': '呜哇！',
		'hyyzlaoyue11': '怎么还没摸到',
		'hyyzmenqing1': '先走闲招。',
		'hyyzmenqing2': '算总账啦。',
		'hyyzangang1': '诶呀，这不就，胡了！',
		'hyyzangang2': '嘭！',

		'hyyz_xt_bailu': '医不自医……',
		'hyyzleiyin1': '乖乖张嘴。',
		'hyyzleiyin2': '补补身子！',
		'xtshengxi1': '我也不能放弃治疗！',
		'xtshengxi2': '疗效好！',
		'hyyzxuanhu1': '我看还能抢救一下！',

		'hyyz_xt_luocha': '没能……实现啊……',
		'hyyzzanghua1': '百花盛放。',
		'hyyzzanghua2': '领受天赐。',
		'hyyzzanghua3': '永眠非终焉。',
		'hyyzzanghua4': '逝者将再临。',
		'hyyzxuanxin1': '凡夺取的，必将偿还。',
		'xtheiyuan1': '清算的时刻到了。',
		'xtheiyuan2': '我来为你送行。',
		'xtbaihua1': '不能松懈。',
		'xtbaihua2': '可惜，你们选错了对手。',

		'hyyz_xt_welt': '交给……你们了……',
		'hyyzduanjie1': '退下吧。',
		'hyyzduanjie2': '让身体和头脑都冷静一下吧。',
		'hyyzduanjie3': '我不会手下留情。',
		'hyyzshenpan1': '这份力量的沉重，你一无所知。',
		'hyyzshenpan2': '见识一下星辰粉碎的样子吧。',
		'hyyzshenpan3': '生存还是毁灭，你别无选择。',

		'hyyz_xt_yinlang': '我……',
		'hyyzhuiya1': '百分百弱点击破。',
		'hyyzhuiya2': '来点刺激的。',
		'hyyzruqin1': '这次能让我玩得开心点吗？',
		'hyyzruqin2': '好，等加强了再来打一次！',
		'hyyzruqin3': '小气，也不多给点。',
		'hyyzfengjin1': '战斗体验该优化了。',
		'hyyzfengjin2': '嘿，就这速度，太慢了！',

		'hyyz_xt_jizi': '明明才刚开始……',
		'hyyzzhuiji1': '小伤。',
		'hyyzzhuiji2': '胆子挺大嘛。',
		'hyyzzhuiji3': '哼，逃不掉的。',
		'hyyzzhuiji4': '战斗是一场精密的设计。',
		'hyyzxinghuo1': '接下来，都是为你准备的！',
		'hyyzxinghuo2': '可要仔细地修理修理。',
		'hyyzxinghuo3': '我当然是来者不拒。',
		'hyyzxinghuo4': '要小心。',
		'hyyztianhuo1': '你可能还不明白，人类从不掩饰掌控星空的欲望，当然，也包括我在内。',
		'hyyzhonglian1': '要拿他练个手吗？',
		'hyyzhonglian2': '燃尽吧！',
		'hyyzhonglian3': '下一次可就没那么简单了。',

		'hyyz_xt_ren': '这次，能成功吗……',
		'hyyzzhuchou1': '你会带给我惊喜吗。',
		'hyyzzhuchou2': '剑下不必留情。',
		'hyyzhuiduo1': '（进入濒死）还不够！',
		'hyyzhuiduo2': '（脱离濒死）可惜，还活着。',
		'hyyzhuiduo3': '悉数奉还！',
		'hyyzhuiduo4': '彼岸，葬送！',
		'hyyzhuiduo5': '以掌中之剑，送你一程。',
		'hyyztushang1': '其势，已成！',
		'hyyztushang2': '死兆，将至！',

		'hyyz_b3_hua': '轩辕……终于可以……',
		'hyyzcunjin1': '嘿！',
		'hyyzcunjin2': '嚯！',
		'hyyzcunjin3': '哈！',
		'hyyzcunjin4': '速战速决！',
		'hyyzcunjin5': '这一次的表现不够完美。',
		'hyyzcunjin6': '清扫战场。',
		'hyyzcunjin7': '时机正好！',
		'hyyzcunjin8': '寸劲！',
		'hyyzcunjin9': '寸劲，开天！',
		'hyyzcunjin10': '山崩！',
		'hyyzcunjin11': '发现弱点！',
		'hyyzshenyin1': '（凤凰鸣叫）',
		'hyyzfusheng1': '长生，于我来说并无他用，能守护好神州足矣。',
		'hyyzfusheng2': '造物推移无定止。昨日欢歌，今日愁烦至。',
		'hyyzfusheng3': '庭前旧梅泛新香。当时故人，如今无在旁。',
		'hyyzfusheng4': '怡然独向九霄中，坐看浮生作梦。',
		'hyyzfusheng5': '时间，冲淡了我的记忆，也冲散了他们的轮廓。',

		'hyyz_xt_bronya': '绝对…不能失守……',
		'hyyzceli1': '时不再至，请助我一臂之力！',
		'hyyzceli2': '时不再至，请随我一同出战！',
		'hyyzceli3': '我们早已踏入风暴。',
		'hyyzceli4': '为了守护和捍卫，击溃他们！',
		'hyyzchuxin1': '我想为「煦日节」找回它原本的意义。',
		'hyyzchuxin2': '或许这就是母亲说的「责任」吧？',
		'hyyzchuxin3': '强敌当前，及时调整战略。',
		'hyyzchuxin4': '将我们所失去的，全部夺回。',
		'hyyzchuxin5': '我们必须铭记，风雪从未消失。',

		'hyyz_xt_sushang': '这下…玩脱了……',
		'hyyzmengdong1': '那词叫啥来着……兵、兵贵神速？总之抓紧点！',
		'hyyzmengdong2': '同样是仙舟人，我俩说的真是一种语言么？',
		'hyyzmengdong3': '浮生一……呃，什么露？韭？',
		'hyyzruoming1': '嗯哼，马上就让你知道我的厉害。',
		'hyyzruoming2': '吃我一招，太虚形蕴！',
		'hyyzruoming3': '小贼，哪里跑！',
		'hyyzhuangwu1': '哎、哎呀，眼睛都看花了……',
		'hyyzhuangwu2': '嘿！小菜一碟！',
		'hyyzhuangwu3': '吓到了吧？这便是云骑军的实力！',

		'hyyz_xt_danhengyinyue': '不该是…现在。',
		'hyyznilin1': '破绽百出。',
		'hyyznilin2': '天洪奔涌…',
		'hyyznilin3': '霄龙现影，破！',
		'hyyznilin4': '神蛟腾云，起！',
		'hyyznilin5': '洞天隐月，苍龙濯世！',
		'hyyznilin6': '潜鳞，已现。',
		'hyyzwangtu1': '那一纸永久流放的命令，倒像是对我的特赦。',
		'hyyzwangtu2': '我不是任何人的影子。',

		'hyyz_b3_kaiwen': '',
		'hyyzqishuang1': '救世，别无他法。',
		'hyyzqishuang2': '在对抗崩坏的道路上，除了胜利，我们别无选择。',
		'hyyzqishuang3': '强大的力量往往意味着更多的责任，同时也意味着巨大的代价。',
		'hyyzshenghen1': '鸟为什么会飞？因为它们，必须飞上天际。',
		'hyyzshenghen2': '鸟儿们想要飞上天际，因此它们为自身打造了双翼。',
		'hyyzshenghen3': '为了不让太阳落下，我飞上天际，将你们的光芒夺去。',
		'hyyzshenghen4': '我将因之融化，坠落于海面。但要想将其夺回，你，你们——必须飞到比我更高的地方。',
		'hyyzshenghen5': '我践踏过无数的理想，无数的生命，也因我而消逝。',
		'hyyzjiushi1': '梵天百兽，加诸此身，「业魔」入渊，「救世」拔剑。',
		'hyyzjiushi2': '此即，救世之铭！',
		'hyyzyemo1': '来吧，我背负的一切！',
		'hyyzyemo2': '这是人类的奇美拉，圣痕的终点。',
		'hyyzyemo3': '这一次我将自己的生命压进枪膛。',
		'hyyzyemo4': '无关乎抉择，无关乎存亡，此刻，万众的理想交会于唯一的宏愿。',

		'hyyz_xt_kaituozhe': '我……必须坚持……',
		'hyyz_kaituo1': '当有机会做出选择的时候，不要让自己后悔。',
		'hyyz_kaituo2': '以自己的意志，抵达结局吧。',
		'hyyzsheming1': '规则，就是用来打破的！',
		'hyyzsheming2': '我来送你上路！',
		'hyyzsheming3': '制胜一击！',
		'hyyzsheming4': '你出局了！',
		'hyyz_huimie1': '不痛不痒。',
		'hyyz_huimie2': '还差得远！',
		'hyyz_huimie3': '速战速决吧。',
		'hyyz_cunhu1': '坚不可摧！',
		'hyyz_cunhu2': '以强援弱！',
		'hyyz_cunhu3': '骑枪，备战！',
		'hyyz_cunhu4': '我来守护！',
		'hyyzzhongwang1': '枪尖已经点燃，炎枪！冲锋！',
		'hyyzzhulian1': '考验默契的时候。',
		'hyyzzhulian2': '各就各位。',
		'hyyzzhulian3': '保持步调一致。',
		'hyyzzhulian4': '即兴表演！',
		'hyyzzhulian5': '好梦成真！',
		'hyyz_tongxie1': '气氛已经烘托到位，合演，开场！',

		'hyyz_xt_jingliu': '终于……解脱了……',
		'hyyzfeiguang1': '阳：剑下草芥。',
		'hyyzfeiguang2': '阳：剑出无回！',
		'hyyzfeiguang3': '转魄阳：你无处可逃！',
		'hyyzfeiguang4': '转魄阳：准备受死！',
		'hyyzfeiguang5': '阴：飞光流泻。',
		'hyyzfeiguang6': '阴：乘月返真。',
		'hyyzfeiguang7': '转魄阴：不能停！不能停下！',
		'hyyzfeiguang8': '转魄阴：现在退下，我便饶你一命。',
		'hyyzzhuanpo1': '阳：就让这一轮月华……照彻万川！',
		'hyyzzhuanpo2': '阳：我以月色为剑！',

		'hyyz_xt_huohuo': '（藿藿）投…投降……',
		'hyyzqienuo1': '（藿藿）这下肯定做不到了……（尾巴）有老子在，你怕什么？',
		'hyyzqienuo2': '（藿藿）又要拖后腿了…',
		'hyyzqienuo3': '（藿藿）说不定我也能做到。',
		'hyyzqienuo4': '（藿藿）呼…看不见我，看不见我…（尾巴）嘿，那边的傻瓜，看这儿看这儿！',
		'hyyzqushen1': '（藿藿）驱邪…缚魅…',
		'hyyzqushen2': '（藿藿）灵符…保命…',
		'hyyzsuiyang1': '（获得岁阳）（藿藿）你、你们不要过来啊…（尾巴）你们这些小崽子，都给我让开…凶神恶鬼，有老子足矣！',
		'hyyzsuiyang2': '（使用岁阳牌）（尾巴）还不谢我？',
		'hyyzsuiyang3': '（使用岁阳牌）（藿藿）谢谢您谢谢您！',
		'hyyzsuiyang4': '（受到伤害时，手中有岁阳牌）（藿藿）尾巴救救！（尾巴）汪！',
		'hyyzsuiyang5': '（受到伤害时，手中有岁阳牌）（藿藿）啊！（尾巴）有种打我！',

		'hyyz_xt_ruanmei': '还没有……答案……',
		'hyyzpeiyu1': '以往的生命片段，还能复原如初吗？',
		'hyyzpeiyu2': '生命，不仅存在于呼吸之间。',
		'hyyzzaowu1': '和之前一样，表现得好，就要奖励。',
		'hyyznicha1': '你仍有值得研究的价值。',
		'hyyznicha2': '很好，优美的姿势。',

		'hyyz_xt_yinzhi': '没找到……「祂」……',
		'hyyzxinyang1': '信念，无可摧毁。',
		'hyyzxinyang2': '献给，伊德莉拉。',
		'hyyzxinyang3': '「纯美」无处不在。',
		'hyyzxinyang4': '我誓令「纯美」之盛名响彻寰宇，至死不泯。',
		'hyyzximei1': '彷徨的人啊，你的目光正看向何方？',
		'hyyzximei2': '银河中的一切美丽，我将捍卫至最后一刻。',
		'hyyzximei3': '一步一行，便无惧陷入泥沼。',

		'hyyz_xt_zhenliyisheng': '庸人吗……',
		'hyyzbianbo1': '（与他人拼点）期待各位的应答。',
		'hyyzbianbo2': '（与他人拼点）让我来考考你。',
		'hyyzbianbo3': '（与自己拼点）不能停止思考。',
		'hyyzbianbo4': '（与自己拼点）人要学会，认识自己。',
		'hyyzbianbo5': '（输了）做的好，+10分。',
		'hyyzbianbo6': '（输了）不错，+5分。',
		'hyyzbianbo7': '（无效）0分，下一个。',
		'hyyzbianbo8': '（受伤）负分，给我滚！',
		'hyyzguina1': '使用记录：存在，即被感知。',
		'hyyzguina2': '财富并非真理的阻碍，而应成为助力。',
		'hyyzguina3': '（归纳）可真是，巧夺天工。',
		'hyyzguina4': '（归纳）以一只玩具的标准，还不错。',

		'hyyz_b3_jiziwuliangta': '真不甘心……',
		'hyyzxiepin1': '呃啊，可恶！',
		'hyyzxiepin2': '别小瞧我。',
		'hyyzxiepin3': '哼，等你好久了。',
		'hyyzxiepin4': '决斗时间。',
		'hyyzxiepin5': '来了吗。',
		'hyyzxiepin6': '你就是我的对手吗？',
		'hyyzxiepin7': '我的力量，还没有达到极限。',
		'hyyzxiepin8': '我会一直战斗到最后一刻。',
		'hyyzxiepin9': '我可没那么脆弱。',
		'hyyzxiepin10': '我不打没有把握的仗。',
		'hyyzpoxiao1': '阳：烈焰焚尽！',
		'hyyzpoxiao2': '阳：烈焰焚尽！',
		'hyyzpoxiao3': '阳：你别想阻止我！',
		'hyyzpoxiao4': '阴：你的攻击结束了吗，那么，现在轮到我了，没意见吧？',
		'hyyzpoxiao5': '阴：你太大意了！',
		'hyyzpoxiao6': '阴：我还能战斗！',
		'hyyzpoxiao7': '阴：不要放弃，永远不要放弃！',
		'hyyzhuozhong1': '活下去，琪亚娜，这就是……最后一课了……',

		'hyyz_xt_huahuo': '玩大了……',
		'hyyzjiaoshi1': '被遗弃的孤儿、受诅咒的少女、人偶一族的末裔...取决于对方喜欢哪个版本吧，我都可以编~',
		'hyyzjiaoshi2': '愚蠢的智者，聪明的愚者…接下来，我会是谁？',
		'hyyzjiaoshi3': '来捉迷藏呀。',
		'hyyzjiaoshi4': '愚者千面，游戏人间…你，会找到答案么？',
		'hyyzkehun1': '再做些大胆的尝试吧？',
		'hyyzkehun2': '玩得开心吗？玩得开心就好！',
		'hyyzkehun3': '规则，就是用来打破的哟~',
		'hyyzkehun4': '我们「愚者」和其他人的区别在于，我们知道自己在表演~',
		'hyyzkehun5': '不能动摇哦。',
		'hyyzkehun6': '再加把劲呢？',

		'hyyz_xt_huangquan': '尘埃...终归大地……',
		'hyyzlunshi1': '我为逝者哀哭......',
		'hyyzlunshi2': '暮雨，终将落下。',
		'hyyzxvwu1': '又多了一份血债。',
		'hyyzxvwu2': '留下回忆之处，触着碰着，都是带刺的花',
		'hyyzxvwu3': '流淌吧...过往的刀光。',
		'hyyzxvwu4': '又是这样。',
		'hyyzxvwu5': '熟悉的感觉......',
		'hyyzanshang1': '此生如朝露，身名俱灭。',
		'hyyzanshang2': '忘川无波澜，引渡徘徊。',

		'hyyz_xt_shajin': '满盘皆输啊……',
		'hyyzniming1': '试试手气。',
		'hyyzniming2': '风险越大，回报越大。',
		'hyyzpoai1': '呵，全押了，我买单。',
		'hyyzpoai2': '哼，不用问，随便花。',
		'hyyzpoai3': '相信我，稳赚不赔。',
		'hyyzpoai4': '呵，这点筹码，可没资格入场。',
		'hyyzpoai5': '诶呀，让我押中了。',
		'hyyzpoai6': '这盘赔率可不小。',
		'hyyzqingzhi1': '骰子已经掷下。',
		'hyyzqingzhi2': '哼，一无所有，或者，赢下所有！',

		'hyyz_liuying': '任务……终止……',
		'hyyzranshang1': '（萨姆）开始清扫。',
		'hyyzranshang2': '（萨姆）目标出现，各单位警戒。',
		'hyyzranshang3': '（流萤）火萤四型，已就位。',
		'hyyzranshang4': '（流萤）这不只是一场战役。',
		'hyyzranshang5': '（流萤）我会为自己夺得胜利。',
		'hyyzranshang6': '（流萤）薄如蝉翼的生命，也有璀璨燃烧的可能。',
		'hyyzranshang7': '（萨姆）进攻，执行。',
		'hyyzranshang8': '（萨姆）预备，起爆。',
		'hyyzranshang9': '（流萤）没有退路，只能向前！',
		'hyyzyingzhu1': '（萨姆&流萤）行动四，点火。',
		'hyyzyingzhu2': '（流萤）为战而生，为生而战。',
		'hyyzyingzhu3': '（流萤）我将，点燃星海！',
		'hyyzyingzhu4': '（萨姆&流萤）飞萤扑火，向死而生。',
		'hyyzyingzhu5': '（萨姆&流萤）我为自我而战，（流萤）直至一切…燃烧殆尽！',

		'hyyz_xt_botiou': '呵呵……好枪法……',
		'hyyzduizhi1': '来吧！公平决斗。',
		'hyyzduizhi2': '放马过来，宝贝！',
		'hyyzduizhi3': '来，动手，成全我。',
		'hyyzduizhi4': '记得那些「道德准则」吗？忘了它们吧！',
		'hyyzxialie1': '我可没说数到三！',
		'hyyzxialie2': '最后这发赏给你！',
		'hyyzxialie3': '开火！',
		'hyyzxialie4': '和你们，已经没道理可讲。',
		'hyyzxialie5': '世上只有两种人——要么手枪上膛…要么自掘坟墓！',
		'hyyzxialie6': '我的脑机芯片可不是用来干这个的。',
		'hyyzxialie7': '没劲，还不如射靶子有意思。',
		'hyyzhenchi1': '排队来吃枪子儿啦？',
		'hyyzhenchi2': '人能不能活下去，靠的就是这个。',

		'hyyz_xt_kafuka': '这还……不是结局……',
		'hyyzmosuo1': '索性都干掉吧！',
		'hyyzmosuo2': '记住还能呼吸的感觉。',
		'hyyzmosuo3': '猎物落网咯。',
		'hyyzmosuo4': '美妙的时光总有尽头，该说再见了。',
		'hyyzyuemian1': '放轻松。',
		'hyyzyuemian2': '站好咯。',

		'hyyz_xt_fuxuan': '事已前定…么……',
		'hyyzshiying1': '相与为一。',
		'hyyzshiying2': '上下象易。',
		'hyyzshiying3': '世间万物自有其法……但换斗移星，谋事，在人！',
		'hyyzqiankun1': '阴阳变转，生生不绝。',
		'hyyzjianzhi1': '物皆自成，无所不利。',
		'hyyzjianzhi2': '风云不测，若涉渊水。',

		'hyyz_xt_heitiane': '流年…不利……',
		'hyyzminggan1': '不祥之征，重现。',
		'hyyzminggan2': '厄运之誓，降临。',
		'hyyzminggan3': '命运，并非一种选择。',
		'hyyzminggan4': '这次想同我了解什么？',
		'hyyzyibu1': '记忆是常变的泡沫。静默的水面下…便是无尽深渊。',

		'hyyz_xt_xier': '我……还能……',
		'hyyzfuguang1': '早点给你个痛快！',
		'hyyzfuguang2': '下一个！',
		'hyyzlixing1': '这就让你解脱！',
		'hyyzlixing2': '麻烦的家伙。',
		'hyyzlixing3': '有目标，镰刀才够快。',
		'hyyzlixing4': '随蝴蝶一起消散吧！',
		'hyyzlixing5': '旧世的幻影！',

		'hyyz_xt_luanpo': '就此，告辞……',
		'hyyzmeiran1': '缭乱•忍法•锦墨绘！',
		'hyyzmeiran2': '缭乱•忍法•万彩绽！',
		'hyyzzhunian1': '银河忍法千变万化，但祓除恶党的忍·信念，未来永劫不变不移。',
		'hyyzzhunian2': '借时为五、还时四，本来无一物，休道莫须有。',
		'hyyzzhunian3': '浮生如夜露，难断生老死苦。',

		'hyyz_xt_zhigengniao': '演出……还没……',
		'hyyzgongming1': '请安静下来。',
		'hyyzgongming2': '谐乐，即将齐奏。',
		'hyyzgongming3': '今夜，灵魂彼此相拥。',
		'hyyzgongming4': '万籁，再次共鸣。',
		'hyyzgongming5': '今夜，群星因我回响。',
		'hyyzlingzhong1': '愿你能在歌中寻得安宁。',
		'hyyzlingzhong2': '愿歌声为我们带来胜利。',
		'hyyzlingzhong3': '希望世间纷争不再。',
	},
	...{//尾巴
		hyyz_xt_kekena: '残梦玫瑰凋未绽，绝望深渊悔恨长。',
		hyyzwanmeng1: '心执一念梦不移，情牵一线歌自扬。',
		hyyzwanmeng2: '抛安逸境觅真我，无志何妨嗅蔷薇。',
		hyyzwanmeng3: '泪洒歌途情未了，心如刀割痛难当。',
		hyyzguizhen1: '理想如炬照夜行，何惧荆棘与寒霜。',
		hyyzguizhen2: '岁月无声泪有痕，泪洒孤城夜未央。',
		hyyzzhiheng1: '繁华落尽空余恨，醉梦问花花不语。',

		hyyz_ys_sp_furina: '别看我……丢人的样子……',
		hyyzshenyi1: '没什么，我没什么想倾诉的，我可是神明芙宁娜，一切都会好起来的！',
		hyyzshenyi2: '唉，真是的，给我点面子啊！',
		hyyzshenyi3: '应对措施也是需要保密的内容！',
		hyyzshenyi4: '哈哈哈哈哈，啊哈哈哈……',
		hyyzshenyi5: '对不起……对不起……',
		hyyzshenyi6: '放弃吧芙宁娜，不要再坚持了……',
		hyyzshenyi7: '好漫长好孤独……还要多久……',
		hyyzshenyi8: '在最后的一刻到来之前，一切都还不算晚。',
		hyyzmantian1: '你们听我说话啊，拜托了，听我说，我真的是神明！',
		hyyzmantian2: '喂，大家，别用这种怀疑的眼神看着我啊！',
		hyyzmantian3: '唉，估计是我身上的水元素过于充盈了~',
		hyyzmantian4: '我，芙卡洛斯，芙宁娜·德·枫丹，尘世七执政之一，众水、众方、众民与众律法的女王，毫无疑问是真正的神明。',
		hyyzmantian5: '我魔神芙卡洛斯，就连世间的诸神都可以审判！',

		hyyz_ys_sp_zhongli: '磐石……也会归于尘土……',
		hyyzfuqiang1: '壁立千仞',
		hyyzfuqiang2: '震天撼地',
		hyyzfuqiang3: '靡坚不摧',
		hyyzfuqiang4: '俱收并蓄',
		hyyzfuqiang5: '安如磐石',
		hyyzfuqiang6: '固若金汤',
		hyyzfuqiang7: '天理长驱',
		hyyzfuqiang8: '此乃天道',
		hyyzfuqiang9: '天动万象',
		hyyzwanglong1: '璃月这个国度的繁荣，靠的是无数响应契约的岩神子民。',
		hyyzwanglong2: '人们交换的不仅仅是金钱与货物，亦有身份、角色与生活的交换。',
		hyyzwanglong3: '你我既有契约之交，那么凡在契约范围内的事，都可同我商量。',
		hyyzwanglong4: '契约已成，如你所求，赐汝应许之物。',

		hyyz_ys_sp_nahida: '生命……终有尽时……',
		hyyzpogu1: '是从什么时候开始的呢？',
		hyyzpogu2: '神明，应该有心声吗。',
		hyyzpogu3: '我好像没有好好聆听过自己的声音，神明也有心声吗？',
		hyyzpogu4: '我自己，究竟是怎么想的呢？',
		hyyzpogu5: '这里，好安静啊。',
		hyyzpogu6: '这里，好安静啊。',
		hyyzpogu7: '我想成为合格的神，为此而不断学习，不断倾听民众的心声，不断找寻拯救世界树的方法，渴望追上那个身影。',
		hyyzpogu8: '我还差的很远，还远远不够格成为一个真正的神明。',
		hyyzpogu9: '我是不是，真的不被需要呢？',
		hyyzpogu10: '我所做的，都是正确的吗？',
		hyyzpogu11: '好像我刚刚，做了一场无比漫长的梦一样，关于我的概念认知，也变得如此清晰。',
		hyyzpogu12: '我不要，再忽视自己的声音了！',
		hyyzpogu13: '想到在我身上发生的很多事情，现在总觉得，好像很生气。',
		hyyzpogu14: '用自己的身体走出牢笼，原来会是这样的心情。',
		hyyzpogu15: '这种感觉，就像月莲找到了莲叶，珊瑚真珠找到了贝壳。',
		hyyzpogu16: '真的谢谢你们大家能来救我，但同时，我也要向你们道歉，这段时间里，我有在好好反思。是我的妄自菲薄，与对教令院迁就，才促成了现在的局面，给你们添了这么多麻烦。',
		hyyzpogu17: '教令院对我所做的一切，我都会以神明的名义，好好报复他们的！',

		hyyz_ys_sp_leidianying: '雷鸣……将歇……',
		hyyzpaoying1: '浮世景色百千年依旧，人之在世却如白露与泡影。虚无。',
		hyyzhuanshi1: '泡影看破！',
		hyyzhuanshi2: '肃清阻碍！',
		hyyzhuanshi3: '威光无赦！',
		hyyzhuanshi4: '枷锁当断。',
		hyyzhuanshi5: '无处遁逃！',
		hyyzhuanshi6: '诸恶当斩。',
		hyyzhuanshi7: '此刻，寂灭之时！',
		hyyzhuanshi8: '稻光，亦是永恒！',
		hyyzhuanshi9: '我会将你，砌进神像里。',
		hyyzhuanshi10: '雷鸣闪电，一瞬即逝。正因如此，才必须掌握「永恒」。',
		hyyzhuanshi11: '虽然身消梦陨，但是她化作了神樱。这，也是「永恒」。',
		hyyzhuanshi12: '你是个例外，例外，是永恒的敌人。',






	},


	...{//2307
		hyyz_xt_sp_sushang: '这下…玩脱了……',
		mengshanqing1: '嗯哼，马上就让你知道我的厉害。',
		mengshanqing2: '吃我一招，太虚形蕴！',
		mengshanqing3: '小贼，哪里跑！',
		mengyouren1: '哎、哎呀，眼睛都看花了……',
		mengyouren2: '嘿！小菜一碟！',
		mengyouren3: '吓到了吧？这便是云骑军的实力！',
		mengwuji1: '那词叫啥来着……兵、兵贵神速？总之抓紧点！',
		mengwuji2: '同样是仙舟人，我俩说的真是一种语言么？',
		mengwuji3: '浮生一……呃，什么露？韭？',

		meng_wu_yvkong: '我无颜面对……',
		mengtianque1: '势如疾风！',
		mengtianque2: '气冲云霄！',
		mengtianque3: '迎风而上吧！',
		mengguanyun1: '风起，云鸢就位。',
		mengguanyun2: '只此，一箭！',

		meng_wu_ren: '这次能成功吗',
		mengwansi1: '此番美景，我虽求而不得……',
		mengwansi2: '却能，邀诸位共赏。',
		mengdibian1: '其势…已成！',
		mengdibian2: '死兆…将至！',
		mengenci1: '你会带给我惊喜么？',
		mengenci2: '剑下不必留情。',
		mengenci3: '悉数…奉还！',
		mengenci4: '彼岸…葬送！',
		mengenci5: '以掌中之剑，送你一程。',
		mengenci6: '你挡路了。',

		hyyz_xt_sp_bronya: '绝对…不能失守……',
		mengzhenjun1: '时不再至，请助我一臂之力！',
		mengzhenjun2: '时不再至，请随我一同出战！',
		mengzhenqu1: '我们早已踏入风暴。',
		mengzhenqu2: '为了守护和捍卫，击溃他们！',
		mengjunzhen1: '拿出魄力来。',
	},
	...{//2308
		meng_xt_jiepade: '我还不能……',
		mengyuhan1: '做好觉悟吧！',
		mengyuhan2: '胜负已分！',
		mengjianyi1: '我以朗道之名，历经冰雪，铸成此志，永不终结！',
		mengjianyi2: '正义已至！',
		mengjianyi3: '有我在。',
		mengjianyi4: '不过如此。',
		mengjianyi5: '小伤而已！',
		mengjueyi1: '奉陪到底。',
		mengjueyi2: '还没到我退场的时候。',

		hyyz_ɸ_xierde: '哇~啊啊~不干了不干了~就这么装死好了……',
		menghengyue1: '希尔德无论是奔跑还是跳跃都很擅长哦，可以从山的这一边跳到那一边！',
		mengguanyang1: '就这点本事，能躲过我的长矛吗？',

		hyyz_xt_kelala: '大家……还好吗……',
		mengdaijia1: '克拉拉要勇敢一点！',
		mengdaijia2: '我……我才不怕你们！',
		mengdaijia3: '我也想保护大家……帮帮我！史瓦罗先生！',
		mengweijia1: '史瓦罗：离开克拉拉。',
		mengweijia2: '史瓦罗：命令执行。',
		//mengweijia2: '史瓦罗：命令执行。',
		//mengweijia2: '史瓦罗：命令执行。',
		mengruyue1: '史瓦罗：歼灭开始！',
		mengruyue2: '史瓦罗：威胁清除。',
		mengruyue3: '克拉拉：史瓦罗先生小心！',
		mengruyue4: '史瓦罗：躲起来。',

		hyyz_b3_sp_xier: '对不起……姐姐……',
		mengshuangsheng1: '不许你们再往前一步了！',
		mengshuangsheng2: '别靠近我！',
		mengshuangsheng3: '哈哈哈，找到你们了！',
		mengshuangsheng4: '你也是来和希儿一起玩的吗？',
		mengshuangsheng5: '感受绝望吧',
		mengbian1: '在黑暗中沦陷吧！',
		mengbian2: '都躲在哪呢？快出来玩吧！',
		mengjuangu1: '拥抱你的力量吧，希儿！',
		mengjuangu2: '外面的世界很危险，希儿……会小心的。',
		mengjuangu3: '希儿……不会再害怕了。',
		mengjuangu4: '希儿……不会再逃避了！',

		meng_alan: '不能保护大家了……',
		mengshinu1: '成全你们，喝！',
		mengshinu2: '都给我闭嘴，喝！',
		mengshinu3: '这点疼痛不足挂齿……',
		mengshinu4: '而你们将会痛苦万倍！',
		mengjianren1: '战斗才能取胜！',
		mengjianren2: '没什么能阻止我！',
		mengjianren3: '活着才能继续战斗！',

		hyyz_b3_kiana: '不可能！绝对不可能……！',
		mengyuehua1: 'Gungnir execution!',
		mengyuehua2: '别小看我！',
		mengyuehua3: '哼，看本小姐大展拳脚！',
		mengliushang1: '现在，是kiana时间！',
		mengliushang2: '光翼展开！',

		hyyz_b3_sb_jiziwuliangta: '这就是……最后……一课了……',
		mengezhan1: '你别想阻止我！',
		mengezhan2: '别想从我手中逃出去！',
		mengzhuoshi1: '你的攻击结束了吗，那么，现在轮到我了，没意见吧？',
		mengzhuoshi2: '烈焰焚尽！',
		mengzhicheng1: '这就是……最后……一课了……',
	},
	...{//2309
		hyyz_b3_sp_jiziwuliangta: '这就是……最后……一课了……',
		mengnuwu1: '你别想阻止我！',
		mengnuwu2: '你太大意了！',
		mengjiezhan1: '别小瞧我！',
		mengjiezhan2: '我还能战斗！',
		mengxinhuo1: '这就是……最后……一课了……',

		hyyz_ys_shenlilingren: '花无百日红……',
		mengwenmou1: '苍流水影。',
		mengwenmou2: '剑影。',
		menggutu1: '秋水三尺。',
		menggutu2: '呵，安息吧。',
		menggutu3: '神里流，水囿。',

		hyyz_b3_lizhilvzhe: '核心……要失去控制了……',
		mengsheyuan1: '量子之海很危险，但布洛妮娅不会退缩！',
		mengsheyuan2: '布洛妮娅想找一样东西，它被遗失在量子之海的深处。',
		mengsheyuan3: '花言巧语，我们不会让你离开这里。',
		mengkanming1: '布洛妮娅，一定不会辜负瓦尔特的意志！',
		mengkanming2: '布洛妮娅也不会改名字，布洛妮娅就是布洛妮娅。',

		hyyz_b3_sushang: '',
		mengzhejian1: '万剑归宗！',
		mengzhejian2: '形随意动！',
		mengtaixu1: '请领教太虚之韵！',
		mengtaixu2: '接下来，本姑娘要动真格的了！',
		mengjianxin1: '用剑之人，当然对宝剑情有独钟。',
		mengjianxin2: '无上自在门大弟子李素裳，承让啦！',

		hyyz_xt_wu_fuxuan: '事已前定…么……',
		mengqiongguan1: '相与为一。',
		mengqiongguan2: '上下象易。',
		mengqiongguan3: '世间万物自有其法……但换斗移星，谋事，在人！',
		mengqiongguan_buff1: '阴阳变转，生生不绝。',
		mengjianzhi1: '物皆自成，无所不利。',
		mengjianzhi2: '风云不测，若涉渊水。',

		hyyz_b3_re_zhongyanzhilvzhe: '',

		hyyz_xt_sb_kafuka: '这还……不是结局……',
		menglaixin1: '我猜不透，哪个答案才是你的真心话。',
		menglaixin2: '你变得很厉害了，也很陌生。',
		menglaixin3: '你真的把自己的想法隐藏得很好呢。',
		menglaixin4: '呼，真令我吃惊，竟然看不透你呢。',
		menglaixin5: '你之所以不记得，是因为执行黑塔计划前，我让你忘了。',
		menglaixin6: '我负责在那之前保护你，教你基本的常识、认知、以及战斗技巧。',
		menglaixin7: '你最终会改变我，我也会改变你，我和你，就是彼此的命运。',
		menglaixin8: '谢谢，你是个好人。',
		mengyueluo1: '过去与未来如此相似，我却对此无动于衷。',
		mengyueluo2: '近乎无限长的时间，近乎无限广的空间，而我们同时出现在一处。命运，就是这样，创造奇迹的同时，让你以为只是偶然。',

		hyyz_b3_luocha: '',
		mengnishang1: '没想到简简单单几步路，横生这么多波折。',
		mengshouwang1: '世上没有绝对的无敌，也没有永恒的不朽。',
		mengshouwang2: '我不出手，你就要受伤了呀。',
		mengwenrun1: '哈哈，姑娘想哪儿去了？',
		mengwenrun2: '在下略懂医术，不如让我试试能否治疗姑娘的伤势。',
		mengwenrun3: '应该不疼，但会有些奇怪的感觉。或许酸，或许麻。可以忍住不动吗？',

		hyyz_ys_shenlilinghua: '我还有……未竟之事……',
		menglinren1: '起舞吧。',
		menglinren2: '失礼了。',
		menglinren3: '雪纷飞。',
		mengqingzi1: '阁下务必小心。',
		mengqingzi2: '烦请赐教。',
		mengqingzi3: '请多关照。',

		hyyz_ɸ_kuisangti: '纳祖芒……屹立不倒！',
		mengxuexing1: '碾碎成沙！',
		mengxuexing2: '够了！',
		mengxuexing3: '粉碎！',
		mengxuexing4: '你走不了了！',
		mengxuexing5: '别跑，给我站住！',
		mengxuexing6: '一刀两断！',
		mengpijing1: '别挡路！',
		mengpijing2: '让开！',
		mengpijing3: '跟我上！',
		mengpijing4: '所向披靡！',
		mengpijing5: '浴血奋战！',
		mengaoan1: '我不会手软！',
		mengaoan2: '你死到临头了！',
		mengaoan3: '我已经受够了！',
		mengaoan4: '呃啊！！！',
		mengaoan5: '要结束了！',
	},
	...{//2310
		meng_sp_ren: '这次能成功吗……',
		mengenciJLP1: '还不够！',
		mengenciJLP2: '可惜，还活着。',
		mengenciJLP3: '悉数奉还！',
		mengenciJLP4: '彼岸，葬送！',
		mengenciJLP5: '以掌中之剑，送你一程。',
		mengkunsheng1: '其势，已成！',
		mengkunsheng2: '死兆，将至！',

		hyyz_xt_sp_kafuka: '这还……不是结局……',
		mengyuemian1: '放轻松。',
		mengyuemian2: '站好咯。',
		mengyexuan1: '索性都干掉吧！',
		mengyexuan2: '记住还能呼吸的感觉。',
		mengyexuan3: '猎物落网咯。',
		mengyexuan4: '美妙的时光总有尽头，该说再见了。',

		meng_re_shalangbaizi: '抱歉，是我判断失误了……',
		meng_shalangbaizi: '抱歉，是我判断失误了……',
		mengjipo1: '有备无患，简单道理',
		mengjipo2: '优秀的指挥，老师',
		mengjipo3: '状态良好，走吧',
		mengjipo4: 'clear',
		mengjiecai1: '上了哦',
		mengjiecai2: '掩护射击',
		mengyouji1: '目标，设立完毕',
		mengyouji2: '开始火力支援',
		mengyouji3: '无人机开始支援',
		mengyouji4: '设备启动',

		hyyz_ys_nuoaier: '我还想……保护大家……',
		mengchawei1: '应该赶得上。',
		mengchawei2: '嗯啊……衣服都弄脏了。',
		mengchawei3: '我不会退缩的。',
		mengchawei4: '没关系，轻伤而已。',
		mengkuangzhu1: '交给我吧！',
		mengkuangzhu2: '交给我吧，什么都可以交给我！',
		mengkuangzhu3: '还有人需要帮忙。',
		mengkuangzhu4: '没关系，不用照顾我的感受的。我为你做的每件事，我都很有成就感哦！',
		mengkuangzhu5: '厨师、园丁、战士、向导……你需要我是什么，我就是什么。',
		mengkuangzhu6: '一定会保护你！',
		mengkuangzhu7: '只要你需要我，我随时都会出现在你的身边。',
		mengjianshou1: '玫瑰在蒙德代表守口如瓶，女仆要严守秘密，所以我很喜欢玫瑰。',
		mengjianshou2: '真高兴！',
		mengjianshou3: '嘿嘿，心满意足。',
		mengjianshou4: '岩石的重量，令人安心。',

		hyyz_ys_qingqizhe: '灰烬里，不是什么也没留下吗？',
		mengsanpan1: '我曾三度遭到背叛，因而懂得世间万物不过是欺瞒的幌子。',
		mengsanpan2: '呵呵呵...哈哈哈哈哈！',
		mengsanpan3: '感谢就免啦，谢来谢去的没意思。',
		mengsanpan4: '若你不畏惧，就站到我身后吧。',
		mengnixin1: '烧掉一个人偶会留下灰烬，至于灰烬中会诞生什么....',
		mengnixin2: '造成伤害：是我疏忽了，抱歉。',
		mengnixin3: '受到伤害：我的胸膛不会再被世俗所染指。',
		menggulu1: '哼，多余。',
		menggulu2: '神明，您认为我是恶吗。',

		hyyz_xt_yanqing: '辜负了……手中三尺……',
		mengjiaoqi1: '剑，如燕跃。',
		mengjiaoqi2: '剑，随我心。',
		mengjiaoqi3: '哼，不过一合之敌。',
		mengjiaoqi4: '略施小计。',
		mengduanao1: '试探就到此为止了。',
		mengduanao2: '万剑，天来！',

		hyyz_b3_chiyuan: '轩辕……终于可以……',
		mengshuyun1: '造物推移无定止。昨日欢歌，今日愁烦至。',
		mengshuyun2: '长生，于我来说并无他用，能守护好神州足矣。',
		mengcaixin1: '怡然独向九霄中，坐看浮生作梦。',
		mengcaixin2: '庭前旧梅泛新香。当时故人，如今无在旁。',
		mengcaixin3: '肃清妖兽，以救神州苍生。',
		mengcaixin4: '阴阳化生，清浊自分。',

		hyyz_b3_shuoyeguanxing: '刺客先生……快走！',
		mengtianfu1: '奇阵已成！',
		mengtianfu2: '其时已至！',
		mengdizai1: '只是一些虫豸罢了。',
		mengdizai2: '虫豸依旧是虫豸。',
		mengfengyang1: '战局千变，皆在吾的计算之中。',
		mengfengyang2: '雕虫小技，不值一提。',

		hyyz_ys_kalilu: '',
	},
	...{//2311
		hyyz_ɸ_yelianna: '',

		hyyz_b3_saixiliya: '',

		hyyz_ys_laiyila: '拜托了，这是个……梦……',
		mengfanqi1: '寒星！',
		mengfanqi2: '拒绝打扰。',
		mengfanqi3: '星星的加护。',
		mengmiansi1: '星辰，为我降下！',
		mengmiansi2: '极寒，让我驱使！',
		mengmiansi3: '别害怕。',

		hyyz_ys_aierhaisen: '接下来就是私人时间了，再见。',
		mengtuiyan1: '发动：理论的推演。',
		mengtuiyan2: '猜对：如果所见即为真实，人就不需要思考了。',
		mengtuiyan3: '猜对：这世上吸引人注意力的东西有很多，不要太相信自己的双眼。',
		mengtuiyan4: '猜错：计划有变。',
		mengtuiyan5: '猜错：我的误算。',
		mengrishen1: '明牌：真理诞生不是为了服务于谁。人类不是知识的载体，知识也不是人类的目的。',
		mengrishen2: '每个人都应该有自己的主张，并始终保持清醒，不然很容易被各种突发状况绑架甚至误入歧途。',
		mengrishen3: '不可响应：比起辞藻的包装，我更喜欢用事实说话。',
		mengrishen4: '据我观察，很多人的烦恼都是自找的，生活中已经有不少难处，就别自添烦忧了。',

		hyyz_b3_xier: 'Seele：不，布洛妮娅姐姐，我……/Vollerei：不要……留下我一个人……',
		mengshuanghun1: '选择Seele：希儿，会和大家一起战斗的。',
		mengshuanghun2: '选择Vollerei：来和希儿一起玩吧！',
		mengsisheng1: '选择Seele：去吧希儿，去守护我们的约定！',
		mengsisheng2: '选择Vollerei：拜托了，另一个我！真拿你没办法',
		mengbaizhou1: '希儿，不会再逃避了。',
		mengbaizhou2: '希儿，不会再害怕了。',
		mengmingguang1: '不能再让姐姐受到任何伤害！',
		mengmingguang2: '现在的希儿，能保护好大家了吗？',
		mengheiye1: '要当希儿的玩具吗？',
		mengheiye2: '给我，死吧！',
		menganying1: '死亡降临！',
		menganying2: '头抬太高了，跪下！',

		hyyz_ys_wu_xiaogong: '祭典，结束了……',

		hyyz_ys_sp_wendy: '哎呀……弦断了……',
		mengliufeng1: '呦吼。',
		mengliufeng2: '在这哟。',
		mengliufeng3: '留意脚下。',
		menggexian1: '哼，别想逃开哦。',
		menggexian2: '起风了。',
		mengbaizhan1: '嘿嘿，要不要感谢「风神的眷顾」呀？',
		mengbaizhan2: '收获不少，可以拿去换几瓶好酒啦。',

		hyyz_ys_abeiduo: '尘归尘，土归土',
		mengsucheng1: '见证伟业吧。',
		mengsucheng2: '此即，诞生之刻。',
		mengsucheng3: '冥古，于此显生。',
		mengchuangsheng1: '绽放吧。',
		mengchuangsheng2: '拟造阳华。',
		mengchuangsheng3: '创生之法。',
		mengbaie1: '大地的秘宝。',
		mengbaie2: '无言的叙事。',

	},
	...{//2312
		meng_zhipeizhilvzhe: '善，是一种需要相信的东西，而恶，不需要！',
		mengzongou1: '人性的卑劣，远比灾难更可怕！',
		mengzongou2: '既然未来比现在更黑暗，那你为什么要劝我看向光明？',
		mengzongou3: '欢迎来到，支配剧场',
		mengzongou4: '是你救了那些折磨我的混蛋！',
		mengzongou5: '灾害没有击垮我们，身为同胞的人类却做到了',
		mengzongou6: '这样的世界，从一开始，就不存在真正的救赎！',
		mengzongou7: '因为那个女人让你活下去，带着贯穿余生的自责与愧疚',
		mengzongou8: '她救了你，却在你心中留下了永远的诅咒！',
		mengzongou9: '也许我的人生，也要到此为止了……',
		mengzongou10: '这种声音，一点一点扩散，变成了丑恶',
		mengzongou11: '这个世界的所有人都是这样，盲目、冲动、自私、悲哀！',
		mengzongou12: '无论付出什么样的代价，都要把你，拉进我们的剧场！',
		mengzongou13: '是时候，给剧目一个收尾了！',
		mengzongou14: '哈哈哈哈！啊哈哈哈哈哈！',

		hyyz_ɸ_zhaoxing: '勇士之魂，从未破灭！',
		mengdianci1: '即使敌众我寡，末将亦能万军从中取敌将首级。',
		mengdianci2: '一点寒芒先到，随后枪出如龙！',
		mengwuwei1: '击鼓，进军！',
		mengwuwei2: '德玛西亚人从不退缩！',
		mengwuwei3: '奉吾王之命！',
		mengwuwei4: '陷阵之志，有死无生！',

		hyyz_xt_wo_danheng: '这……不可能！',
		menggufeng1: '生死虚实，一念之间。',
		menggufeng2: '洞天幻化，长梦一觉，破！',
		menggufeng3: '现在后悔已经迟了。',
		menggufeng4: '切忌冲动行事。',
		mengqinghua1: '还好，不难。',
		mengqinghua2: '顺利就好。',

		hyyz_xt_tuopa: '我没填……事假申请……',
		mengzhaiquan1: '还不还款？',
		mengshougou1: '清算时间到啦！',
		mengshougou2: '连本带息，还债！',
		mengshougou3: '全部资产，没收！',
		mengshicha1: '开始吧，资产评估。',
		mengshicha2: '市场波动很正常，该出手时就出手吧！',
		mengshicha3: '目光放远，聚焦长线，就是成功投资的秘诀。',

		hyyz_xt_aisida: '还想知道更多……',
		menglisi1: '每一颗星星，都是一颗奇迹。',
		menglisi2: '了解的事越多，就越喜欢这片星空。',
		menglisi3: '目标就如星辰一般，并非都是遥不可及哦！',
		mengshanzhi1: '是啊，如果我不努力工作，就要回去继承家业了。',
		mengshanzhi2: '幸运儿，会是哪个呢？',
		mengchuxin1: '星辰，会铭记我们的名字！',
		mengchuxin2: '嗯，品质还算上乘。',

		hyyz_ys_hutao: '',
		mengxifeng: '',
		mengliaoshi: '',
		mengwansheng: '',
		mengwansheng_rewrite: '',

		meng_jiutiao: '生命终非永恒……',
		mengyayu1: '我一个人，就是一只幕府军！',
		mengyayu2: '雷闪！',
		mengyayu3: '羽移。',
		mengyayu4: '散！',
		mengyu1: '满意的弦音，看我一击即中！',
		mengyu2: '与你并肩。',
		mengyu3: '我会带领你获得胜利。',
		mengyu4: '我会坚持到底！',
		mengwuyan1: '常道恢弘，鸣神永恒！',
		mengwuyan2: '雷光千道！',
	},
	...{//2401
		hyyz_b3_aiyi: '任务失败，需要重新计算。',
		mengmiaobu1: '系统更新完成，运行速度提升。',
		mengmiaobu2: '敌方解析结果：威胁性较高。',
		mengmiaobu3: '符合计算。',
		mengmiaobu4: '修正误差。',
		mengmiaobu5: '哎呀，看来是恶性bug呢。',
		mengyansuan1: '怎么就这点？根本不够嘛。',
		mengyansuan2: '双马尾加速。',
		mengyansuan3: '能量装填进度100%。',

		hyyz_b3_re_xinyanzhilvzhe: '我还能继续燃烧',

		hyyz_xt_sp_jingyuan: '久疏战阵了……',
		menglaoshen1: '兵戈，无情！',
		menglaoshen2: '雷霆，在此！',
		'hyyzshence1': '临军对阵，持重待机便可。',
		'hyyzshence2': '急如律令。',
		'hyyzshence3': '随我冲阵！',
		'hyyzshence4': '时不我待！',

		hyyz_xt_sp_ruanmei: '这儿要是「模拟宇宙」，就由着你任性了。',
		mengtansheng1: '生命，不仅存在于呼吸之间。',
		mengtansheng2: '这便是生命的温度吗？',
		mengtansheng3: '作为当助手的回报，我可以给你奖励，任何你想要的我都可以满足。',
		mengzidian1: '休息一下，茶点时间到了。',
		mengzidian2: '亲爱的，注意安全。',

		hyyz_xt_guinaifen: '诶……演砸了……',
		mengzhuyi1: '生活呀就是忙忙碌碌，人生呢还有慢慢体会。',
		mengzhuyi2: '技多不压身，功到自然成！',
		mengzhuyi3: '有钱的捧个钱场！',
		mengzhuyi4: '没钱的下次一定！',
		menghenhuo1: '瞧一瞧，看一看嘞！机会难得，给您拜个早年吧！',
		mengtangcai1: '嚯哟哟，还有意外收获！',
		mengtangcai2: '幸亏我练过！',
		mengtangcai3: '还来劲啦你！',

		hyyz_xt_luka: '不能……这么狼狈……',
		menghanxin1: '对付你，一拳就够了。',
		menghanxin2: '哼，不过是条杂鱼。',
		menghanxin3: '这一拳，送你回家！',
		menghanxin4: '有点意思',
		menghanxin5: '小意思',
		mengquanzhi1: '咱俩合作，没有打不赢的架！',
		mengquanzhi2: '怎样，要认输吗？',
		mengquanzhi3: '打击恶棍，守护镇民，这就是我每天的工作。',

		hyyz_ys_baizhu: '人死，灯灭……',
		mengzhenyao1: '良药苦口呀。',
		mengzhenyao2: '得治治！',
		mengzhenyao3: '是药三分毒！',
		mengwenji1: '须知惜命。',
		mengwenji2: '病宜速救。',
		mengwenji3: '且尝，苦尽甘来。',

		hyyz_xt_sp_fuxuan: '事已前定…么……',

		hyyz_ys_sb_nahida: '生命……终有尽时……',

		hyyz_ys_furina: '别看我……丢人的样子……',
		mengjvxing1: '1：喂，大家，别用这种怀疑的眼神看着我啊！',
		mengjvxing2: '2：唉，估计是我身上的水元素过于充盈了~',
		mengjvxing3: '3：我，芙卡洛斯，芙宁娜·德·枫丹，尘世七执政之一，众水、众方、众民与众律法的女王，毫无疑问是真正的神明。',
		mengjvxing4: '4：我魔神芙卡洛斯，就连世间的诸神都可以审判！',
		mengjvxing5: '成功：天理，不可与之为敌，预言中的那一幕，一定会发生。',
		mengjvxing6: '失败：你们听我说话啊，拜托了，听我说，我真的是神明！',
		mengjvxing7: '入场：欢迎来到水的国度！',
		mengshenyi1: '出牌阶段失去明置牌12：我是否已经到了极限呢？',
		mengshenyi2: '出牌阶段失去明置牌3：这样下去的话，所有人都会得救。',
		mengshenyi3: '出牌阶段失去明置牌45：在最后的一刻到来之前，一切都还不算晚。',
		mengshenyi4: '出牌阶段失去暗置牌12：对不起……对不起……',
		mengshenyi5: '出牌阶段失去暗置牌3：好漫长好孤独……还要多久……',
		mengshenyi6: '出牌阶段失去暗置牌45：放弃吧芙宁娜，不要再坚持了……',
		mengshenyi7: '装备栏回至12：应对措施也是需要保密的内容！',
		mengshenyi8: '装备栏回至3：唉，真是的，给我点面子啊！',
		mengshenyi9: '装备栏回至45：哈哈哈哈哈，啊哈哈哈……',
		mengshenyi10: '装备栏废至1：你要干什么……不要杀我，求求你！',
		mengshenyi11: '装备栏废至2：没什么，我没什么想倾诉的，我可是神明芙宁娜，一切都会好起来的！',
		mengshenyi12: '装备栏废至3：没有！我从来都没有轻视过预言，也从没有悠闲度日！',
		mengshenyi13: '装备栏废至45：你怎么知道我在想什么？',
		mengshenyi_rewrite1: '水应该不会淹上来吧……',
		mengshenyi_rewrite2: '噔噔！',
		mengshenyi_rewrite3: '欢唱，以我之名！',
		mengshenyi_rewrite4: '亮相啦！',
		mengshenyi_rewrite5: '让世界热闹起来吧！',
		mengshenyi_rewrite6: '闪耀时刻！',
		mengrensheng1: '摸牌阶段：既然这样，就让你我共同出演我们的未来吧！',
		mengrensheng2: '摸牌阶段：渐入佳境！不愧是我，在任何情况下都能展现出闪耀的一面。',
		mengrensheng3: '弃牌阶段：情况不妙啊！',
		mengrensheng4: '弃牌阶段：过去的种种经历组成了现在的我，那场并不完美的演出也是我最重要的一部分啊。',

		hyyz_ys_zhongli: '磐石……也会归于尘土……',
		menglvheng1: '让人们遵循契约，其实是希望人们能遵循公平。',
		menglvheng2: '不以规矩，不能成方圆。',
		menglvheng3: '交易的规矩是契约，准则是公平。',
		menglvheng4: '璃月这个国度的繁荣，靠的是无数响应契约的岩神子民。',
		menglvheng5: '人们交换的不仅仅是金钱与货物，亦有身份、角色与生活的交换。',
		menglvheng6: '偶遇之物，亦有风雅。',
		menglvheng7: '你我既有契约之交，那么凡在契约范围内的事，都可同我商量。',
		menglvheng8: '契约已成，如你所求，赐汝应许之物。',
		mengminhui1: '天动万象。',

		hyyz_ys_nahida: '生命……终有尽时……',
		mengkunchu1: '是从什么时候开始的呢？',
		mengkunchu2: '神明，应该有心声吗。',
		mengkunchu3: '我好像没有好好聆听过自己的声音，神明也有心声吗？',
		mengkunchu4: '我自己，究竟是怎么想的呢？',
		mengkunchu5: '这里，好安静啊。',
		mengkunchu6: '这里，好安静啊。',
		mengkunchu7: '我想成为合格的神，为此而不断学习，不断倾听民众的心声，不断找寻拯救世界树的方法，渴望追上那个身影。',
		mengkunchu8: '我还差的很远，还远远不够格成为一个真正的神明。',
		mengkunchu9: '我是不是，真的不被需要呢？',
		mengkunchu10: '我所做的，都是正确的吗？',
		mengkunchu11: '好像我刚刚，做了一场无比漫长的梦一样，关于我的概念认知，也变得如此清晰。',
		mengkunchu12: '我不要，再忽视自己的声音了！',
		mengkunchu13: '想到在我身上发生的很多事情，现在总觉得，好像很生气。',
		mengkunchu14: '用自己的身体走出牢笼，原来会是这样的心情。',
		mengkunchu15: '这种感觉，就像月莲找到了莲叶，珊瑚真珠找到了贝壳。',
		mengkunchu16: '真的谢谢你们大家能来救我，但同时，我也要向你们道歉，这段时间里，我有在好好反思。是我的妄自菲薄，与对教令院迁就，才促成了现在的局面，给你们添了这么多麻烦。',
		mengkunchu17: '教令院对我所做的一切，我都会以神明的名义，好好报复他们的！',
		mengxvkong1: '正是因为我们不会飞，才会无比向往天空。',
		mengxvkong2: '比喻是可以用已知知识去理解未知知识的奇妙工具哦！',
		mengxvkong3: '对智慧者而言，普通人的凡庸是一种与生俱来的错吗？那都是「我们」不可分割的一部分。',
		mengxvkong4: '智慧并不取决于知道些什么，而是取决于可以改变些什么。',
		mengxvkong5: '神明只送给人类填饱肚子的知识，人类却借此制作了工具，书写了文字，壮大了城邦。',
		mengxvkong6: '世间万物，周而复始，谓之轮回。',
		mengxvkong7: '我们无法观测未来的所有可能性，只能靠这样略显笨拙的方式获取知识。',
		mengxvkong8: '这世上有太多的东西，都是过时不候的呢。',

		hyyz_ys_leidianying: '雷鸣……将歇……',
		mengwuwang1: '泡影看破！',
		mengwuwang2: '肃清阻碍！',
		mengwuwang3: '威光无赦！',
		mengwuwang4: '枷锁当断。',
		mengwuwang5: '无处遁逃！',
		mengwuwang6: '诸恶当斩。',
		mengwuwang7: '「磨损」是一件很可怕的事情。此身诞生的意义，就是承受磨损。',
		mengwuxiang1: '「初传」之位，可以学习太刀的九向剑路之势',
		mengwuxiang2: '「中传」之位，太刀术需要研习各种「构」位与变化',
		mengwuxiang3: '「皆传」之位，需要研习诸般奥义。',
		mengwuxiang4: '雷鸣闪电，一瞬即逝。正因如此，才必须掌握「永恒」。',
		mengwunian1: '虽然身消梦陨，但是她化作了神樱。这，也是「永恒」。',
		mengwumeng1: '你是个例外，例外，是永恒的敌人',
		mengwumeng2: '我会将你，砌进神像里。',
		mengwuwo1: '追求永恒，可能也只是一种逃避罢了。',

		hyyz_ys_wendy: '哎呀……弦断了……',
	},
	...{//2402
		hyyz_xt_danhengbailu: '',

		hyyz_ɸ_pink: '江山娇矣…红旗漫乎…（胜利：江山娇也！红旗漫也！）',
		mengyingzhu1: '先辅：玄甲耀目，朱旗绛天！',
		mengyingzhu2: '先辅：干云气惊八万里，一键光寒十九州！',
		mengyingzhu3: '受伤：为国除弊，怎惜残年！',
		mengyingzhu4: '受伤：接天连夜无穷碧，映日荷花别样红！',
		mengyingzhu5: '获得偶给的牌：姐妹们，爱国真的有用！',
		mengyingzhu6: '获得偶给的牌：耶！被阿中哥哥表扬了！',
		mengqiongpi1: '偶获得牌：蠢尔蛮荆，大邦为仇！',
		mengqiongpi2: '偶获得牌：威动四极，武义直方！',
		mengqiongpi3: '偶造成伤害：摅高文之宿愤，光祖宗之玄灵！',
		mengqiongpi4: '偶造成伤害：拓后嗣之境宇，振华夏之天声！',
		mengqiongpi5: '你获得牌：饭圈出征，寸草不生！',
		mengqiongpi6: '你获得牌：守护我们最好的阿中哥哥！',
		mengqiongpi7: '你造成伤害：不服国命，纵兵凶战危，也应以血相偿！',
		mengqiongpi8: '你造成伤害：花墙霸屏金鼓震，饭圈起兮万人随！',
		mengqiongpi9: '被逆：不惧千夫指，但求无愧心！',
		mengqiongpi10: '被逆：你们指责我，就说明我做对了！',
		mengqiongpi11: '使命失败：主公，臣妾无异心呐！',
		mengqiongpi12: '使命失败：铁拳怎么砸到我身上了？',

		hyyz_ys_shanhugongxinhai: '计策…出问题了吗？',
		mengchengxin1: '帮帮忙！',
		mengchengxin2: '别担心。',
		mengchengxin3: '休养生息。',
		mengshouyuan1: '沧海之约。',
		mengshouyuan2: '翻涌吧！',
		mengshouyuan3: '深海的加护！',

		meng_wu_jingyuan: '久疏战阵了……',

		hyyz_xt_sp_luocha: '没能……实现啊……',

		hyyz_xt_natasha: '我可是医生啊……',
		mengjiuhu1: '吃药了',
		mengjiuhu2: '不疼了吧',
		mengyizhex1: '一场精妙的手术',
		mengyizhex2: '一点心意而已，不必在意',
	},
	...{//2403
		hyyz_b3_zhongyanzhilvzhe: '',
		mengzhaoxi1: '一击……必杀！',
		mengzhaoxi2: '预备……点火！',
		mengzhaoxi3: '一箭……制胜！',
		mengpingji1: 'kiana时间。',
		mengpingji2: 'kiana时间！',
		mengcifan1: '过好每一天，道路自然会延伸。',
		mengcifan2: '我来为你们开辟前路。',

		hyyz_b3_xinyanzhilvzhe: '我还能继续燃烧',
		mengliaohuang1: '薪炎，拔剑！',
		mengliaohuang2: '预备，点火！',
		mengliaohuang3: '赴火，蹈刃！',
		mengliaohuang4: '烈焰，焚尽！',
		mengjingmang1: '以此烈火，斩无不断！',
		mengjingmang2: '审判的时刻到了！',
		mengjingmang3: '决战的时刻到了！',

		hyyz_xt_shiwaluo: '',//魈的代码真*

		hyyz_xt_wangxiayitong: '',

		hyyz_xt_sp_heitiane: '流年…不利……',
		mengzhenzhao1: '无理的客人',
		mengzhenzhao2: '必将承受代价！',
		mengshuijing1: '不祥之征，重现。',
		mengshuijing2: '厄运之誓，降临。',
		mengshuijing3: '命运，并非一种选择。',
		mengshuijing4: '这次想同我了解什么？',
		mengshuijing_end1: '记忆是常变的泡沫。静默的水面下…便是无尽深渊。',
		mengliuguang1: '不祥之征，重现。',
		mengliuguang2: '厄运之誓，降临。',
		mengliuguang3: '命运，并非一种选择。',
		mengliuguang4: '这次想同我了解什么？',

		hyyz_xt_sb_jingliu: '终于……解脱了……',
		mengzuanyue1: '就让这一轮月华……照彻万川！',
		mengzuanyue2: '我以月色为剑！',
		mengshishui1: '剑下草芥。',
		mengshishui2: '剑出无回！',
		mengshishui3: '你无处可逃！',
		mengshishui4: '准备受死！',
		mengshishui5: '飞光流泻。',
		mengshishui6: '乘月返真。',
		mengshishui7: '不能停！不能停下！',
		mengshishui8: '现在退下，我便饶你一命。',

		hyyz_xt_sangbo: '这下赔大了……',
		mengdahun1: '我桑博一向关照朋友',
		mengdahun2: '你帮我，我当然帮你',
		mengdahun3: '又有生意上门了',
		mengdahun4: '权当找点乐子吧',
		mengdahun5: '欠你个人情',

		hyyz_ys_leidianzhen: '',

	},
	...{//2404meng_sp_leidianyayi
		hyyz_b3_sp_leidianyayi: '',

		hyyz_xt_lingke: "哥…姐……",
		mengjuejing1: '为了去往远方…',
		mengjuejing2: '不管什么手段，通通拿出来吧！',
		mengxueyuan1: '放松，深呼吸。',
		mengxueyuan2: '补充点盐分。',
		mengqiusheng1: '啊，被叮了个包…',
		mengqiusheng2: '得快点止血。',

		hyyz_ɸ_luotianyi: '',

		hyyz_xt_sp_shajin: '满盘皆输啊……',
		mengyanglu1: '呵，全押了，我买单。',
		mengyanglu2: '哼，不用问，随便花。',
		mengyanglu3: '相信我，稳赚不赔。',
		mengtuipan1: '试试手气。',
		mengtuipan2: '风险越大，回报越大。',
		mengtuipan3: '呵，这点筹码，可没资格入场。',
		mengtuipan4: '诶呀，让我押中了。',
		mengtuipan5: '这盘赔率可不小。',
	},
	...{//2407
		hyyz_xt_wu_liuying: '任务……终止……',
		mengliuguangzhuhuo1: '（萨姆）开始清扫。',
		mengliuguangzhuhuo2: '（萨姆）目标出现，各单位警戒。',
		mengliuguangzhuhuo3: '（流萤）火萤四型，已就位。',
		mengliuguangzhuhuo4: '（流萤）这不只是一场战役。',
		mengliuguangzhuhuo5: '（流萤）我会为自己夺得胜利。',
		mengliuguangzhuhuo6: '（流萤）薄如蝉翼的生命，也有璀璨燃烧的可能。',
		mengliuguangzhuhuo7: '（萨姆）进攻，执行。',
		mengliuguangzhuhuo8: '（萨姆）预备，起爆。',
		mengliuguangzhuhuo9: '（流萤）没有退路，只能向前！',
		mengmengguihechu1: '（萨姆&流萤）行动四，点火。',
		mengmengguihechu2: '（流萤）为战而生，为生而战。',
		mengmengguihechu3: '（流萤）我将，点燃星海！',
		mengmengguihechu4: '（萨姆&流萤）飞萤扑火，向死而生。',
		mengmengguihechu5: '（萨姆&流萤）我为自我而战，（流萤）直至一切…燃烧殆尽！',

		hyyz_xt_re_liuying: '任务……终止……',

		hyyz_xt_sp_liuying: '任务……终止……',
	},
	...{//2408hyyz_b3_leidianyayi
		hyyz_xt_sb_ruanmei: '还没有……答案……',
		mengdanqinghuiqianqiu1: '你仍有值得研究的价值。',
		mengdanqinghuiqianqiu2: '很好，优美的姿势。',

		hyyz_ys_xiaogong: '祭典，结束了……',
		mengyanshi1: '想看烟花吗？',
		mengyanshi2: '点燃引信！',
		mengyanshi3: '小心火烛！',
		mengqingcun1: '祭典重现！',
		mengqingcun2: '金鱼来啦！',
		menghuahuoyouyi1: '烟花来咯！',

		hyyz_xt_sp_botiou: '呵呵……好枪法……',
		mengxunhai1: '来吧！公平决斗。',
		mengxunhai2: '放马过来，宝贝！',
		mengxunhai3: '来，动手，成全我。',
		mengxunhai4: '记得那些「道德准则」吗？忘了它们吧！',
		menghuxing1: '我可没说数到三！',
		menghuxing2: '最后这发赏给你！',
		menghuxing3: '开火！',
		menghuxing4: '和你们，已经没道理可讲。',
		menghuxing5: '世上只有两种人——要么手枪上膛…要么自掘坟墓！',
		menghuxing6: '我的脑机芯片可不是用来干这个的。',
		menghuxing7: '没劲，还不如射靶子有意思。',
		mengjueming1: '排队来吃枪子儿啦？',
		mengjueming2: '人能不能活下去，靠的就是这个。',

		hyyz_b3_leidianyayi: '',
		menglizui: '',
		mengchengshi: '',
		mengwange: '',

		hyyz_ys_sb_zhongli: '磐石……也会归于尘土……',

		meng_feixiao: '各位…拜托了……',
		mengyueguan1: '不避，不悔！',
		mengyueguan2: '无惧，无畏！',
		mengleishou1: '我将，巡征追猎。',
		mengleishou2: '翾翔不坠，万载常胜！',
		mengleishou3: '太慢！',
		mengleishou4: '不行。',
		mengleishou5: '大捷，已定！',
		mengtiantong1: '良机就在当下。',

		hyyz_xt_sp_sanyueqi: '江湖…难啊……',
		mengxijian1: '师父请喝茶！',
		mengxijian2: '劳您担待啦！',
		menghuiwu1: '看我这招！',
		menghuiwu2: '看我的绝招！',
	},
	...{//2409
		hyyz_ɸ_xi: '',

		hyyz_ɸ_chunjin_aiyafala: '',

		hyyz_xt_sb_fuxuan: '事已前定…么……',

		hyyz_ys_fukaluosi: '',
	},
	...{//2410
		hyyz_b3_sp_hua: '轩辕……终于可以……',
	},
	...{//2411
		hyyz_xt_moze: '功亏…一篑……',
		mengcangfeng1: '我，即是锋刃……',
		mengcangfeng2: '我，即是阴影……',
		mengniying1: '该收割了。',
		mengniying2: '风声所到之处…你无所遁形！',
		mengjiandai1: '时机，转瞬即逝。',
		mengjiandai2: '夜色，如影随形。',
		mengjiandai3: '幽冥，奔袭！',

		hyyz_xt_heita: '断开…连接……',
		mengaixing1: '有人问我灵感是什么，不就是脑中一分钟几千次的波动吗',
		mengaixing2: '既不解题，又不写稿，那就别怪自己的人生无趣咯',
		mengwoxiang1: '就这样吧，人偶而已，别要求太多。',
		mengwoxiang2: '我已经够完美了，还有什么事要做？',

		hyyz_ys_kaqina: '对不起……是我逞强了……',
		mengduoji1: '冲地波！',
		mengduoji2: '清退！',
		mengduoji3: '矿石采集。',
		mengduoji4: '切勿靠近。',

		hyyz_b3_sp_meibiwusi: '',

		hyyz_b3_weierwei: '',
	},
	...{//2412
		hyyz_ys_xigewen: '还有病人在等我…',
		mengyiyv1: '别动哟',
		mengyiyv2: '我看看',
		mengyiyv3: '冷静',
		mengyiyv4: '吹泡泡',
		mengyiyv5: '晃悠悠',
		mengyiyv6: '飘乎乎',
		mengyvzan1: '谨誓！精研医理',
		mengyvzan2: '别紧张哦，放松',
		mengyvzan3: '医嘱：即刻注射',
		mengyirong1: '看来得强制治疗了…',
		mengyirong2: '救援到了！',

		hyyz_ɸ_dinyi: '朝闻道，夕死可矣。',
		mengwendao1: '当生命意识到宇宙奥秘存在时，据他解开这个奥秘只有一步之遥了。',
		mengwendao2: '智慧生命有多种悲哀，这只是其中之一。',
		mengwendao3: '你把宇宙终极的奥秘告诉我，然后，毁灭我。',
		mengwendao4: '对宇宙终极真理的追求，是文明的最终目标和归宿。',
		mengwendao5: '所有生活都是合理的，我们没有必要相互理解。',
		mengwendao6: '科学发展到现在，终于有人对他的本质进行了比较准确的定义。',
		mengwendao7: '我们，看完了。',
		mengwendao8: '当宇宙的和谐之美一览无余地展现在你面前时，生命只是一个小小的代价。',

		hyyz_xt_wangguiren: '命定如此吗……',
		mengruoxi1: '流云易散。',
		mengruoxi2: '长梦已醒。',
		mengruoxi3: '有福不妨同享。',
		mengruoxi4: '同心一意可好？',
		mengwuguiWGR1: '前尘旧梦，俱已往矣。',
		mengwuguiWGR2: '生命纵如微尘，亦能翩然起舞。',

		hyyz_xt_sb_shajin: '满盘皆输啊……',
		mengcifu1: '骰子已经掷下。',
		mengcifu2: '哼，一无所有，或者，赢下所有！',

		hyyz_ɸ_cuicui: '',

		hyyz_zzz_xingjianya: '别像过去那么逞强……',
		mengliyi1: '还没结束。',
		mengliyi2: '有两下子。',
		mengliyi3: '正合我意。',
		mengliyi4: '我会再闪一次。',
		mengqixue1: '接招！',
		mengqixue2: '我看到了！',
		mengqixue3: '机不可失！',
		mengqixue4: '喝！',
		mengqixue5: '喝！',
		mengqixue6: '于此，斩！',
		mengqixue7: '以此刀为誓！',
		mengqixue8: '恶！即斩！',
		mengqixue9: '胜为上，战次之！',
		mengchenling_hyyz_zzz_xingjianya1: '归鞘！',
		mengchenling_hyyz_zzz_xingjianya2: '结束了。',
		mengchenling_hyyz_zzz_xingjianya3: '吾心如明镜。',
		mengchenling_hyyz_zzz_xingjianya4: '半明半昧半尺间！',

		meng_xier: '不，布洛妮娅姐姐，我……',

		hyyz_xt_sp_daheita: '我还会回来……',
		mengqiuda1: '新世界的大门',
		mengqiuda2: '就得打开思路',
		mengqiuda3: '洞见未知的瞬间，为它沉迷吧。',
		mengqiuda4: '筑就空域的壁垒，就此塌落吧。',
		mengqiuda5: '好奇心可是很危险的',
		mengqiuda6: '谜题千千万万，但谜底却是…乌有之物。',

		'hyyz_xt_sp_zhigengniao': '演出……还没……',
		menghesong1: '请安静下来。',
		menghesong2: '谐乐，即将齐奏。',
		menghesong3: '今夜，灵魂彼此相拥。',
		menghesong4: '万籁，再次共鸣。',
		menghesong5: '今夜，群星因我回响。',
		mengxiezou1: '愿你能在歌中寻得安宁。',
		mengxiezou2: '愿歌声为我们带来胜利。',
		mengxiezou3: '希望世间纷争不再。',
	},
	...{//2501
		hyyz_xt_yvkong: '我无颜面对……',
		mengxiaowang1: '天之苍苍，鸢之所向。',//
		mengxiaowang2: '或许…我的心从未远离这片星空。',
		mengxiaowang3: '迎风而上吧！',
		mengxiaowang4: '风起，云鸢就位。',
		mengxiaowang5: '只此，一箭！',
		mengqingping1: '并无大碍！',
		mengqingping2: '呃啊，各位小心！',
		mengqingping3: '从起飞开始，于降落结束，才称得上是圆满、完整的飞行。',
		mengyunjin1: '多加练习，方可更加熟练。',
		mengyunjin2: '对待劲敌，不可掉以轻心。',
		mengchenling_hyyz_xt_yvkong1: '势如疾风！',
		mengchenling_hyyz_xt_yvkong2: '气冲云霄！',
		mengchenling_hyyz_xt_yvkong3: '干戈未止！',
		mengchenling_hyyz_xt_yvkong4: '星海迢迢，道阻且长。',

		hyyz_ɸ_miyali: '现在的我，没有办法原谅当时的我的所作所为…',
		mengsanyin1: '（让食物变美味的咒语）',
		mengshuren1: '你在跟一个杀人犯讲理性？！',

		hyyz_ɸ_anjielina: '',

		hyyz_xt_sp_tingyun: '命定如此吗……',

		hyyz_zzz_sb_bonisi: '',

		hyyz_ɸ_king: '这是个轮回，永远无法打破的轮回。',
		mengshouguan1: '此天时地利，何不加冕为王？',
		mengshouguan2: '除旧王，立新王，此为辞旧迎新。',
		mengzhushiK1: '前为主公赴汤蹈火，此等赏赐，应由吾先领赏。',

		hyyz_xt_tibao: '明天见……',
		mengxunhuan1: '缇安：给我冲呀！ 缇宝：BANG！',
		mengxunhuan2: '缇安：走——起飞咯！ 缇宝：棒！',
		mengchenyv1: '缇宝：特大喜讯~ 缇宁：喏。',
		mengchenyv2: '缇宝：送温暖啦~ 缇宁：嗯！',
		mengfeixiang1: '太好啦，我们又见面啦。',
		mengfeixiang2: '小瞧我们可是会吃亏的。',

	},
	...{//2502
		mengsimingzhangluyixiebozhi1: '千邦荡平，万军成灰',
		mengsimingzhangluyixiebozhi2: '千邦荡平，万军成灰',
		mengtianchiwuxingbingxianqianli1: '天谴降，皆奠纷争昂藏',
		mengtianchiwuxingbingxianqianli2: '天谴降，皆奠纷争昂藏',
		mengtianchiwuxingbingxianqianli3: '天谴降，皆奠纷争昂藏',
		mengtianchiwuxingbingxianqianli4: '天谴降，皆奠纷争昂藏',
	},
	...{//2503
		mengchongshi1: '仙宫中也和人间一样，有高低贵贱之分。',
		mengchongshi2: '就因为我是豹子精修炼成人，是是门中唯一的异类！',
		mengchongshi3: '我虽然出身妖族，身份卑贱，却有一颗得道成仙的心。',
		mengkunmiu1: '人心中的成见是一座大山，任你怎么努力都休想搬动！',
		mengkunmiu2: '跟你一样，我也是妖族……',
		mengkunmiu3: '即使我已经位列仙班，但依旧摆脱不了妖的标签。',
		mengkunmiu4: '要凭借自身优秀，改变人心中的成见，但我每一次得到的都是失望。',
		mengkunmiu5: '他总是赐给我师兄太乙真人数不尽的法宝，而我只有一根铁棍！',

		hyyz_ys_youla: "罪人的结局吗……",
		mengzuchou1: '求饶吧。',
		mengzuchou2: '结霜！',
		mengzuchou3: '粉化！',
		mengzuchou4: '判决！',
		mengzuchou5: '破碎！',
		mengzuchou6: '以眼还眼！',
		menghailang1: '冰浪怒涛！',
		menghailang2: '以霜还怨！',
		menghailang3: '坚冰，断绝深仇！',

		hyyz_xt_yunli: '爷爷……',
		mengjiandan1: '上决浮云，喝——',
		mengjiandan2: '下绝地纪，灭——',
		mengkanpo1: '碎——岩——破！',
		mengkanpo2: '崩——剑——斩！',
		mengkanpo3: '截云，断岳！',
		mengkanpo4: '剑出，山倾！',
	},
	...{//2504
		hyyz_ys_yianshan: '这下练出事了...',
		mengtuantie1: '风驰电掣！',
		mengtuantie2: '更快，更强！',
		mengshengtong1: '调整呼吸！',
		mengshengtong2: '动起来！',
		mengjiulong1: '计时开始！',
		mengjiulong2: '听我的口号！',

		hyyz_ys_aikefei: '讨厌的味道...',
		mengliaoqie1: '冷冻时间。',
		mengliaoqie2: '餐前甜点。',
		mengliaoqie3: '低温处理。',
		mengliaoqie4: '即兴烹饪。',
		mengliaoqie5: '顺从灵感的搭配..',
		mengliaoqie6: '希望会有惊喜。',
		mengjinhui1: '如雪雁般...振翅！',
		mengjinhui2: '臻品呈现！',
		mengjinhui3: '形与味，进发！',
	},
	...{//2505
		hyyz_xt_sb_daheita: '我还会回来……',
	},
	...{//2506
		hyyz_ys_sikeke: '星海默然，覆灭无声…',
		mengyuanxin1: '尽没。',
		mengyuanxin2: '湮散。',
		mengyuanxin3: '溢流。',
		mengyuanxin4: '破空。',
		mengyuanxin5: '踏刃。',
		mengfengyv1: '沉于渊海。',
		mengfengyv2: '群星寂灭。',
		mengfengyv3: '更迭万象。',
		mengfengyv4: '力量啊.',
		mengfengyv5: '归于我。',

		hyyz_xt_fengjin: '先祖，我还没...',
		mengpiye1: '是得好好晒个太阳～',
		mengpiye2: '大家等我们很久啦~',
		mengyvqiong1: '愿这一抹微光....拨开阴与云雾，重见澄澈晴空！',

		hyyz_ys_mengjianyueruixi: '噩梦，蔓延了...',
		mengqiyi1: '别皱眉呀。',
		mengqiyi2: '美梦疗法。',
		mengqiyi3: '镇定下来。',
		mengqianmeng1: '噩梦噩梦快离开..',
		mengqianmeng2: '来吧，小安，小彻。',
		mengqianmeng3: '「..晓时枕醒春风。」',

		hyyz_xt_saifeier: '',
		mengfanfei1: '财宝...让我吸吸！',
		mengfanfei2: '猫咪...大开口！',
		mengfanfei3: '随便玩玩的把戏结束了。',
		mengfanfei4: '一人传虚，万人传实。骗到你咯~',
	},


	ym_zilinggudelige: '白天爆肝，晚上圆梦，粉丝白嫖，万万不可呀',
	ymgengxin1: '勤学潜习，今日更新。',
	ymgengxin2: '骊歌更新，如视天光破云。',
	ymgengxin3: '欢迎收看本期视频。',
	ymgengxin4: '大家好，我是紫灵谷的骊歌！',
	ymsanlian1: '非常感谢各位小伙伴的三连。',
	ymsanlian2: '一张：得此点赞，必得大道。',
	ymsanlian3: '两张：得此投币，骊歌定可高枕无忧。',
	ymsanlian4: '三张：将军三连关注，大汉之栋梁也！',
	ymzhenggao1: '诶，这位小伙伴设计得不错诶。',
	ymzhenggao2: '嗷，你的技能好复杂呀。',
	ymyuanmeng1: '闻汝设计俱佳，今特圆梦相请。',
	ymyuanmeng2: '闻将军著有武将一卷，容骊歌观之。',
	ymyuanmeng3: '交之三连，付之圆梦。',
	ymduangeng1: '力不竭，鸽不止。',
	ymduangeng2: '粉丝催更百天，却难抵吾断更三日！',

	ym_weibajiang: '沧浪之水，纵浊万物亦不可濯心。',
	ymzhuxin1: '锐评不在多，一语可诛心！',
	ymzhuxin2: '语如刃牙，洞若观心。',
	ymyingping1: '自驯者驯傲，驯人者驯拙。',
	ymyingping2: '苛言苛行，忿厉何故',
	ymzhuojian1: '目瞭则形无不分，心敏则理无不达。',
	ymzhuojian2: '胸中存灼见，眼底辨秋毫。',

	ym_canghaiyisu: '',

	ym_re_canghaiyisu: '',

	ym_menghai: '星消夜长鸣，月落与山行…/victory:长夜终至，诸君，我们已迈向远方！',
	ymyingji1: '无论你逃往何处，我的剑永远如影随形。',
	ymyingji2: '今夜即将消散的，除了那漫天星辰…还有你我。',
	ymanxing1: '面临自我生命消散之际，每个人都会显露内心。',
	ymanxing2: '身上的枷锁沉重，也不会影响到明天，且待前路。',

	ym_sp_menghai: '时来天地皆同力，运去英雄不自由',
	ymspxingmeng1: '星河景明，万物竞发，岂容汝等宵小妄为？',
	ymspxingmeng2: '今夜良辰，我当效用破敌！',
	ymspxingmeng3: '俱怀逸兴壮思飞，欲上青天览明月。',
	ymlangu1: '良辰美酒，当与诸君共勉。',
	ymlangu2: '赏罚有度，可振吾军雄风。',
	ymlangu3: '指点江山，激扬文字，粪土当年万户侯。',

	ym_miealiei: '唔啊！师傅你好坑啊！( ﾉД`)',
	ymxunshi1: '刚入门诶，找哪位师傅好呢？',
	ymxunshi2: '灵感不足的时候啊，只能看师傅，学师傅，发现跑偏骂师傅！',
	ymzaobing1: '只有学好了这些技巧，才能做好我的武将嘛！',
	ympanli1: '师傅太过分！我要去单干啦！',
	ymzaobing_rewrite1: '设计与玩法，机制与强度一个也不能落下。',
	ymjingxiu1: '准备好了吗？动手吧！',

	ym_sp_miealiei: '难逃一劫了吗，不要啊，把你的大宝拿开',
	ymkunlv1: '得想个法子把你踹下来，不然我会难受',
	ymsiyan1: '失败，就是胯下之辱，成功，就是永久凌驾',
	ymsiling1: '啊，我有权看透你的一切，也有权让你失去你的一切',

	ym_youyi: '这位为了不断完善自我而准备潜水的旅行者到底是谁呢？.......没错，就是我。',
	ymzhumeng1: '纵使梦路难行，亦当砥砺奋进！',
	ymzhumeng2: '鸟飞反故乡兮，狐死必首丘。',
	ymgongmian1: '良作，与你分享~',
	ymgongmian2: '兼善妙染，当一而再，再而三。',

	ym_sp_youyi: '还是，回不去了吗',
	ymtihan1: '',
	ymtihan2: '',
	ymwennuan1: '',
	ymwennuan2: '',

	ym_lalalala: '再见，再也不见。/我只是想….交个朋友。/victory:咱们真强。',
	ymanli1: 'van～',
	ymanli2: '好玩得很。',
	ymanli3: '跟你说个事哦，贼～逆天哦。',
	ymanli4: '使命成功：哈哈哈哈！',
	ymanli5: '使命失败：哈哈哈哈（大笑，转哭腔）',
	ymanli6: '`游戏`被使用：你看吧，我就说是神作。',
	ymanli7: '咋样，好玩吧？',
	ymanli8: '`游戏`被弃置：每个人受众不同嘛（逐渐小声）',
	ymanli9: '没事，这个确实不是很好玩。',
	ymyongle1: '最开心的一集。',
	ymyongle2: '有我，你就偷着乐吧。',
	ymguli1: '你也别想好过。',
	ymguli2: '没人会在意我的，也没人会在意你的。',

	ym_rijiu: '梦……该醒了。/victory:迷蝶醉卧乱花丛，日高起，雨朦胧，覆手翻云，万紫千红一念成。',
	ymxuanxiang1: '喜挽华彩遍地，巧织蜃景漫天。',
	ymxuanxiang2: '轻抚锦瑟五十，慢采星辰万千。',
	ymhuanying1: '瑰丽奇幻，偶得一人化天地。',
	ymhuanying2: '大梦初醒，方知童稚痴幼行。',
	ymxiaoxing1: '我思，则千象初生。',
	ymxiaoxing2: '我见，故万物恒常。',

	ym_xilin: '溜了溜了，打游戏去了',
	ymdiaotu1: '这有一份图，要不让他们也看看？',
	ymle1: '为了解决红眼病的问题，各界人士启动了名为乐的计划',

	ym_zhouwang: '止步于此，何谈永恒？',
	ymhumeng1: '咒禁。',
	ymhumeng2: '敕！',
	ymhumeng3: '显化。',
	ymhumeng4: '留形。',
	ymhumeng5: '雷霆侘寂！',
	ymhumeng6: '雷光凄美啊。',
	ymhumeng7: '真瞳显现！',
	ymqiuyu1: '律令。',
	ymqiuyu2: '真是麻烦',

	ym_re_miealiei: '没关系的没关系的，设计这么多，睡着放松一下也不是不行啦',
	ymfanxing1: '重锱前进，劳神伤心',
	ymqinglv1: '卸锱轻行，快意逍遥',
}
export default hyyzvoices 